---
- name: MariaDB playbook
  hosts: amco
  become: true
  become_method: sudo
  tasks:
    
    - name: Install MySQL(depreacted now MariaDB)
      apt:
        name: default-mysql-server
        state: latest
    
    - name: Install PyMySQL
      apt:
        name: python-mysqldb
        state: latest
    
    - name: Copy database dump file
      copy:
        src: dump.sql
        dest: /tmp

    - name: Create MySQL database
      mysql_db:
        name: KinkonyDB
        state: import
        target: /tmp/dump.sql